consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  Account:
    description: Account (default view)
    example:
      name: John
    properties:
      name:
        description: name
        example: John
        type: string
    title: 'Mediatype identifier: application/vnd.account+json; view=default'
    type: object
  AccountCollection:
    description: AccountCollection is the media type for an array of Account (default
      view)
    example:
    - name: John
    - name: John
    items:
      $ref: '#/definitions/Account'
    title: 'Mediatype identifier: application/vnd.account+json; type=collection; view=default'
    type: array
  CreateAccountPayload:
    example:
      name: John
    properties:
      name:
        description: name
        example: John
        type: string
    required:
    - name
    title: CreateAccountPayload
    type: object
  DeleteAccountPayload:
    example:
      name: John
    properties:
      name:
        description: name
        example: John
        type: string
    required:
    - name
    title: DeleteAccountPayload
    type: object
  UpdateAccountPayload:
    example:
      name: John
    properties:
      name:
        description: name
        example: John
        type: string
    required:
    - name
    title: UpdateAccountPayload
    type: object
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
host: localhost:8080
info:
  description: A simple appengine example
  title: The appengine example
  version: ""
paths:
  /account:
    get:
      description: list
      operationId: Account#list
      produces:
      - application/vnd.goa.error
      - application/vnd.goa.error
      - application/vnd.account+json; type=collection
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/AccountCollection'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: list Account
      tags:
      - Account
    post:
      description: create
      operationId: Account#create
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/CreateAccountPayload'
      produces:
      - application/vnd.goa.error
      - application/vnd.goa.error
      - application/vnd.account+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Account'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: create Account
      tags:
      - Account
  /account/{id}:
    delete:
      description: delete
      operationId: Account#delete
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/DeleteAccountPayload'
      produces:
      - application/vnd.goa.error
      - application/vnd.goa.error
      - application/vnd.account+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Account'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: delete Account
      tags:
      - Account
    get:
      description: show
      operationId: Account#show
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: name
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/vnd.goa.error
      - application/vnd.goa.error
      - application/vnd.account+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Account'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: show Account
      tags:
      - Account
    put:
      description: update
      operationId: Account#update
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UpdateAccountPayload'
      produces:
      - application/vnd.goa.error
      - application/vnd.goa.error
      - application/vnd.account+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Account'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: update Account
      tags:
      - Account
  /swagger.json:
    get:
      operationId: swagger#/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
      summary: Download swagger/swagger.json
  /swagger/{filepath}:
    get:
      operationId: swagger#/swagger/*filepath
      parameters:
      - description: Relative file path
        in: path
        name: filepath
        required: true
        type: string
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
        "404":
          description: File not found
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: Download public/swagger/
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  OK:
    description: OK
    schema:
      $ref: '#/definitions/Account'
schemes:
- http
swagger: "2.0"
