// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "appengine": swagger TestHelpers
//
// Command:
// $ goagen
// --design=github.com/pei0804/goa-datastore/design
// --out=$(GOPATH)/src/github.com/pei0804/goa-datastore
// --version=v1.2.0-dirty

package test
